services:
  - type: web
    name: strumsense-audio-analysis
    env: docker
    plan: free
    rootDir: python-service
    dockerfilePath: ./Dockerfile
    envVars:
      - key: ACOUSTID_API_KEY
        value: bQjVA25JFn
      - key: GENIUS_API_KEY
        sync: false
